name: common
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

#flutter pub run build_runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.4.0
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1
  google_sign_in: ^5.3.0
  flutter_riverpod: ^1.0.3
  firebase_storage: ^10.2.12
  firebase_messaging: ^11.2.13
  cloud_firestore: ^3.1.12
  google_fonts: ^2.3.1
  url_launcher: ^6.0.20
  intl: ^0.17.0
  percent_indicator: ^3.4.0
  image_picker: ^0.8.5
  connectivity_plus: ^2.3.0
  audioplayers: ^0.20.1
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^1.1.1
  build_runner: ^2.1.10
  json_serializable: ^6.1.6
flutter:

  uses-material-design: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
